INSERT INTO Bil(bilMerke, bilType) VALUES('AUDI','A5');
INSERT INTO Bil(bilMerke, bilType) VALUES('AUDI','A6');
INSERT INTO Bil(bilMerke, bilType) VALUES('AUDI','A7');
INSERT INTO Bil(bilMerke, bilType) VALUES('NISSAN','N1');
INSERT INTO Bil(bilMerke, bilType) VALUES('NISSAN','N2');
INSERT INTO Bil(bilMerke, bilType) VALUES('NISSAN','N3');
INSERT INTO Bil(bilMerke, bilType) VALUES('KIA','K9');
INSERT INTO Bil(bilMerke, bilType) VALUES('KIA','K10');
INSERT INTO Bil(bilMerke, bilType) VALUES('KIA','K11');